CREATE TABLE KYC_DOCUMENTS (
                               document_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                               customer_id     NUMBER NOT NULL,
                               document_name   VARCHAR2(255 CHAR) NOT NULL,
                               document_type   VARCHAR2(100 CHAR) NOT NULL,
                               document_content BLOB NOT NULL,
                               status          VARCHAR2(20 CHAR) DEFAULT 'PENDING',
                               message         VARCHAR2(1000 CHAR),
                               verified_by     VARCHAR2(255 CHAR),
                               uploaded_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

                               CONSTRAINT fk_kyc_customer FOREIGN KEY (customer_id)
                                   REFERENCES CUSTOMERS (customer_id)
                                   ON DELETE CASCADE
);
